// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 17.2.2026, 21:49:03
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/home/philipp-ottlinger/Dokumente/KODOIA/Development/Coding/KoProjects/frontend/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/philipp-ottlinger/Dokumente/KODOIA/Development/Coding/KoProjects/frontend/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/philipp-ottlinger/Dokumente/KODOIA/Development/Coding/KoProjects/frontend/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/philipp-ottlinger/Dokumente/KODOIA/Development/Coding/KoProjects/frontend/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/philipp-ottlinger/Dokumente/KODOIA/Development/Coding/KoProjects/frontend/app/plugins/**/*.{js,ts,mjs}","/home/philipp-ottlinger/Dokumente/KODOIA/Development/Coding/KoProjects/frontend/app/composables/**/*.{js,ts,mjs}","/home/philipp-ottlinger/Dokumente/KODOIA/Development/Coding/KoProjects/frontend/app/utils/**/*.{js,ts,mjs}","/home/philipp-ottlinger/Dokumente/KODOIA/Development/Coding/KoProjects/frontend/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/philipp-ottlinger/Dokumente/KODOIA/Development/Coding/KoProjects/frontend/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/philipp-ottlinger/Dokumente/KODOIA/Development/Coding/KoProjects/frontend/app/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;